name: pppos
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

isar_version: &isar_version 3.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0 # contains Isar Core  
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  easy_localization: ^3.0.3
  flutter_launcher_icons: ^0.13.1
  rename_app: ^1.3.1
  flutter_native_splash: ^2.3.7
  sprintf: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0
  build_runner: any

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/languages/
    - assets/languages/icons/
    - assets/images/logos/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

